stages:
  - build
  - publish
  - deploy

variables:
  DOCKER_IMAGE: "dulno-core-workflow"
  DOCKER_DOCS_IMAGE: "dulno-core-workflow-docs"

build:
  stage: build
  image: gradle:8.12.0-jdk21
  script:
    - gradle jar
    - gradle javadoc
  artifacts:
    paths:
      - build/libs/
      - build/docs/javadoc/
    expire_in: 1 day

publish:
  stage: publish
  image: docker:cli
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  dependencies:
    - build
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:latest .
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
    - docker buildx build -t $DOCKER_REGISTRY/$DOCKER_DOCS_IMAGE:latest -f docs/Dockerfile .
    - docker push $DOCKER_REGISTRY/$DOCKER_DOCS_IMAGE:latest
  only:
    - master

deploy_core:
  stage: deploy
  trigger:
    project: $CORE_PIPELINE_PROJECT
    branch: $CORE_PIPELINE_BRANCH
  only:
    - master

deploy_wiki:
  stage: deploy
  trigger:
    project: $WIKI_PIPELINE_PROJECT
    branch: $WIKI_PIPELINE_BRANCH
  only:
    - master