stages:
  - build
  - publish
  - deploy
  - merge

variables:
  DOCKER_IMAGE: "dulno-core-workflow"
  DOCKER_DOCS_IMAGE: "dulno-core-workflow-docs"

build:
  stage: build
  image: gradle:8.13.0-jdk21
  script:
    - gradle jar
    - gradle publish
    - gradle javadoc
  artifacts:
    paths:
      - build/libs/
      - build/docs/javadoc/
    expire_in: 1 day

publish_staging:
  stage: publish
  image: docker:cli
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  dependencies:
    - build
  script:
    - echo $STAGING_DOCKER_PASSWORD | docker login -u $STAGING_DOCKER_USERNAME --password-stdin $STAGING_DOCKER_REGISTRY
    - docker build -t $STAGING_DOCKER_REGISTRY/$DOCKER_IMAGE:latest .
    - docker push $STAGING_DOCKER_REGISTRY/$DOCKER_IMAGE:latest
    - docker buildx build -t $STAGING_DOCKER_REGISTRY/$DOCKER_DOCS_IMAGE:latest -f docs/Dockerfile .
    - docker push $STAGING_DOCKER_REGISTRY/$DOCKER_DOCS_IMAGE:latest
  only:
    - dev

publish_productive:
  stage: publish
  image: docker:cli
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  dependencies:
    - build
  script:
    - echo $PRODUCTIVE_DOCKER_PASSWORD | docker login -u $PRODUCTIVE_DOCKER_USERNAME --password-stdin $PRODUCTIVE_DOCKER_REGISTRY
    - docker build -t $PRODUCTIVE_DOCKER_REGISTRY/$DOCKER_IMAGE:latest .
    - docker push $PRODUCTIVE_DOCKER_REGISTRY/$DOCKER_IMAGE:latest
    - docker buildx build -t $PRODUCTIVE_DOCKER_REGISTRY/$DOCKER_DOCS_IMAGE:latest -f docs/Dockerfile .
    - docker push $PRODUCTIVE_DOCKER_REGISTRY/$DOCKER_DOCS_IMAGE:latest
  only:
    - main

deploy_staging:
  stage: deploy
  trigger:
    project: $CORE_PIPELINE_PROJECT
    branch: dev
  only:
    - dev
  when: manual

deploy_productive:
  stage: deploy
  trigger:
    project: $CORE_PIPELINE_PROJECT
    branch: main
  only:
    - main
  when: manual

merge:
  stage: merge
  image: curlimages/curl:latest
  script:
    - |
      curl --request POST --header "PRIVATE-TOKEN: $DULNO_GITLAB_PRIVATE_TOKEN" \
      --data "source_branch=dev&target_branch=main&title=Production deployment" \
      --data "remove_source_branch=false&squash=true" \
      "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/merge_requests"
  only:
    - dev
  when: on_success